# -*- coding: utf-8 -*-
"""nenealbum.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S5Xnr2lcua4giP-MbUfAMxTDdYG5GCBZ
"""

import pandas as pd
import tweepy

consumer_key ="aMX9jop92dfIKfzR6P5h5Bl4J"
consumer_secret ="4kw51PDF21FprG1TU5Fh6vQ5NwiNIPgMjMqQjPS29aPjv6VfQz"
access_token="1207985460804407296-XKu24OJHj0pHDX6E5KaSHF8QZcVuyM"
access_token_secret ="SjugDY7xcXZ9xFr9HsgbGq3jJ6WOuxuAmcLvHy9nQEgU5"
 
# Twitterオブジェクトの生成
auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)
api = tweepy.API(auth)
 
 #ツイートを取得
fanart_user = []
fanart_id = []
q = "#ねねアルバム" 
tweets = api.search(q, count=100)
for tweet in tweets:
  user = tweet.user.screen_name
  fanart_user.append(user)

for tweet in tweets:
  id = tweet.id
  fanart_id.append(id)

fanart_id_str = list(map(str,fanart_id))
#idを置き換える
fanart_pre_url = []
for pre_id in fanart_id_str:
  pre_url= "https://twitter.com/user/status/id"
  url = pre_url.replace('id' , pre_id)
  fanart_pre_url.append(url)
#userを置き換える
fanart_url = []
i = 0
for url in fanart_pre_url:
  true_url = url.replace('user',fanart_user[i])
  fanart_url.append(true_url)
  i +=1

df_user = pd.DataFrame(fanart_user)
df_id = pd.DataFrame(fanart_id)
df_fanart = pd.DataFrame(fanart_url)
df_fanart_master = pd.concat([df_user,df_id,df_fanart],axis=1)
df_fanart_master.to_csv("fanart.csv")